security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Omega\NAOBundle\Entity\Utilisateurs: plaintext

    role_hierarchy:
        ROLE_PARTICULIER: ROLE_USER
        ROLE_NATURALISTE: [ROLE_USER, ROLE_PARTICULIER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_PARTICULIER, ROLE_NATURALISTE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
              entity:
                class:    Omega\NAOBundle\Entity\Utilisateurs
                property: username

        api:
            entity:
                class: Omega\NAOBundle\Entity\Utilisateurs
                property: googleId

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /

            guard:
                authenticators: 
                    - omega_nao.authenticator

    access_control:
        - { path: ^/moderation-observation, roles: ROLE_NATURALISTE }
        - { path: ^/moderation-compte, roles: ROLE_ADMIN }