services:

    omega_nao.datataxref:
        class: Omega\NAOBundle\DataAutoComplete\DataTaxref
        arguments:
            - "@doctrine.orm.entity_manager"

    omega_nao.upload:
        class: Omega\NAOBundle\UploadedFile\UploadedPhotos
        arguments:
            $targetDir: '%img_directory%'

    NAOBundle.mail:
            class: Omega\NAOBundle\Services\MailService

    omega_nao.validator.espece:
        class: Omega\NAOBundle\Validator\VerifespeceValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: omega_nao_espece }

    NAOBundle.mailInscription :
            class: Omega\NAOBundle\Services\MailInscriptionService

    NAOBundle.FacebookLogin :
            class: Omega\NAOBundle\Services\FacebookLoginService

