services:

    omega_nao.datataxref:
        class: Omega\NAOBundle\DataAutoComplete\DataTaxref
        arguments:
            - "@doctrine.orm.entity_manager"

    omega_nao.upload:
        class: Omega\NAOBundle\UploadedFile\UploadedPhotos
        arguments:
            $targetDir: '%img_directory%'

    NAOBundle.mail:
            class: Omega\NAOBundle\Services\MailService

