services:

    omega_nao.datataxref:
        class: Omega\NAOBundle\Services\DataTaxrefService
        arguments:
            - "@doctrine.orm.entity_manager"

    omega_nao.upload:
        class: Omega\NAOBundle\Services\UploadedPhotosService
        arguments:
            $targetDir: '%img_directory%'

    NAOBundle.mail:
            class: Omega\NAOBundle\Services\MailService

    omega_nao.validator.espece:
        class: Omega\NAOBundle\Validator\VerifespeceValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: omega_nao_espece }

    NAOBundle.mailInscription :
            class: Omega\NAOBundle\Services\MailInscriptionService


    omega_nao.authenticator:
        class: Omega\NAOBundle\Services\TokenAuthenticatorService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"

    NAOBundle.FacebookLogin :
            class: Omega\NAOBundle\Services\FacebookLoginService
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@router"

    NAOBundle.authenticatorFB:
            class: Omega\NAOBundle\Facebook\TokenAuthenticatorFBService
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@router"

    omega_nao.index:
        class: Omega\NAOBundle\Services\IndexService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.authorization_checker"

    omega_nao.add_obs:
        class: Omega\NAOBundle\Services\AddObservationService
        arguments:
            - "@omega_nao.upload"
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
            - "@session"

    omega_nao.moderation_compte:
        class: Omega\NAOBundle\Services\ModerationCompteService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"
            - "@NAOBundle.mail"
            - "@session"

    omega_nao.moderation_observation:
        class: Omega\NAOBundle\Services\ModerationObservationService
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@templating"
            - "@NAOBundle.mail"
            - "@session"
            - "@omega_nao.upload"

    omega_nao.register_google:
        class: Omega\NAOBundle\Services\InscriptionGoogleService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"
            - "@NAOBundle.mail"

    omega_nao.change_compte:
        class: Omega\NAOBundle\Services\ChangeCompteService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@session"

